all: readlines-main
 
readlines-main: readlines-main.o readlines.o
        gcc readlines-main.o readlines.o -o readlines-main
 
readlines-main.o:
        gcc -c readlines-main.c
       
readlines.o:
        gcc -c readlines.o